name: SFDX Deploy
description: Deploy your Salesforce changes using an sfdx auth file
author: Zackary Frazier

inputs:
  auth-file:
    description: 'The path to the auth file file'
    required: true
    default: 'authFile.json'
  branch:
    description: 'The branch to compare against'
    required: true
    default: 'origin/master'
  quick-deploy-id:
    description: 'The id of the quick deploy to deploy'
    required: false
    default: ''
  out-file:
    description: 'The file to output the deploy results to'
    required: false
    default: 'deploy.json'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install SFDX
      shell: bash
      run: |
        npm i -g @salesforce/cli
        sf --version
        echo y | sf plugins install sfdx-git-delta
    - name: Authenticate
      shell: bash
      run: | 
        sf org login sfdx-url --sfdx-url-file "${{ inputs.auth-file }}" --set-default-dev-hub --alias DevHub
    - name: Quick Deploy
      if: ${{ inputs.quick-deploy-id != '' }}
      shell: bash
      run: |
        sf project deploy quick --job-id "${{ inputs.quick-deploy-id }}" -o DevHub --json > ${{ inputs.out-file }}
    - name: Deploy Delta
      if: ${{ inputs.quick-deploy-id == '' }}
      shell: bash
      run: |
        sf sgd source delta --to "HEAD" --from "${{ inputs.branch }}" --output "." 
        sf project deploy start --test-level RunLocalTests --manifest package/package.xml -o DevHub -w 120 --json --pre-destructive-changes ./destructiveChanges/destructiveChanges.xml > deploy.json